apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
spec:
  project: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: "3.7.1"
      chart: k8s-monitoring
      helm:
        valueFiles:
          - $values/charts/argocd-applications/values/alloy-values.yaml
          - $values/charts/argocd-applications/values/alloy-{{ required ".Values.cluster_name is required" .Values.cluster_name }}-values.yaml
        valuesObject:
          vault_name: '{{ required ".Values.vault_name is required" .Values.vault_name }}'
          cluster_name: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
          cluster:
            name: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
          destinations:
            - name: localMimir
              type: prometheus
              url: http://mimir-gateway.mimir.svc/api/v1/push
              tenantId: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
              secret:
                create: false
                embed: true
            - name: localLoki
              type: loki
              url: http://loki.loki.svc:3100/loki/api/v1/push
              tenantId: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
              secret:
                create: false
                embed: true
          extraObjects:
            - apiVersion: monitoring.coreos.com/v1
              kind: Probe
              metadata:
                name: hubitat-http
                namespace: "alloy"
              spec:
                interval: 30s
                module: http_2xx
                prober:
                  url: alloy-alloy-metrics-cluster.alloy.svc:12345
                  path: /api/v0/component/prometheus.exporter.blackbox.blackbox_exporter/probe
                targets:
                  staticConfig:
                    static:
                      - http://hubitat.local.symmatree.com
            - apiVersion: monitoring.coreos.com/v1
              kind: Probe
              metadata:
                name: raconteur-syno-ui
                namespace: "alloy"
              spec:
                interval: 30s
                module: http_2xx
                prober:
                  url: alloy-alloy-metrics-cluster.alloy.svc:12345
                  path: /api/v0/component/prometheus.exporter.blackbox.blackbox_exporter/probe
                targets:
                  staticConfig:
                    static:
                      - https://raconteur.ad.local.symmatree.com:5001/
            - apiVersion: monitoring.coreos.com/v1
              kind: Probe
              metadata:
                name: morpheus-ui
                namespace: "alloy"
              spec:
                interval: 30s
                module: http_2xx
                prober:
                  url: alloy-alloy-metrics-cluster.alloy.svc:12345
                  path: /api/v0/component/prometheus.exporter.blackbox.blackbox_exporter/probe
                targets:
                  staticConfig:
                    static:
                      - https://morpheus.local.symmatree.com/
            - apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: otlp-ingress
                namespace: "alloy"
                annotations:
                  cert-manager.io/cluster-issuer: real-cert
                  external-dns.alpha.kubernetes.io/hostname: 'otlp.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com'
              spec:
                ingressClassName: cilium
                tls:
                  - secretName: otlp-tls
                    hosts:
                      - 'otlp.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com'
                rules:
                  - host: 'otlp.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com'
                    http:
                      paths:
                        - path: /
                          pathType: Prefix
                          backend:
                            service:
                              name: alloy-alloy-receiver
                              port:
                                number: 4318
          alloy-singleton:
            extraConfig: |-
              mimir.rules.kubernetes "default" {
                address = "http://mimir-gateway.mimir.svc"
                tenant_id = "{{ required ".Values.cluster_name is required" .Values.cluster_name }}"
              }
    - repoURL: https://github.com/symmatree/tiles.git
      targetRevision: '{{ required ".Values.targetRevision is required" .Values.targetRevision }}'
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
        trust-bundle: enabled
