apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: "10.4.2"
      chart: grafana
      helm:
        valueFiles:
          - $values/charts/argocd-applications/values/grafana-values.yaml
          - $values/charts/argocd-applications/values/grafana-{{ required ".Values.cluster_name is required" .Values.cluster_name }}-values.yaml
        valuesObject:
          vault_name: '{{ required ".Values.vault_name is required" .Values.vault_name }}'
          cluster_name: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
          ingress:
            hosts:
              - 'borgmon.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com'
            tls:
              - secretName: grafana-tls
                hosts:
                  - 'borgmon.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com'
          extraObjects:
            - apiVersion: onepassword.com/v1
              kind: OnePasswordItem
              metadata:
                namespace: "grafana"
                name: github-data-source-secret
                labels:
                  grafana_datasource: "1"
              type: Opaque
              spec:
                itemPath: "vaults/{{.Values.vault_name}}/items/grafana-github-token"
            - apiVersion: onepassword.com/v1
              kind: OnePasswordItem
              metadata:
                namespace: "grafana"
                name: grafana-admin-user
              type: Opaque
              spec:
                itemPath: "vaults/{{.Values.vault_name}}/items/grafana-admin-user"
          grafana.ini:
            server:
              root_url: 'https://borgmon.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com/'
    - repoURL: https://github.com/symmatree/tiles.git
      targetRevision: '{{ required ".Values.targetRevision is required" .Values.targetRevision }}'
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/warn: baseline
        trust-bundle: enabled
