apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  project: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: "6.49.0"
      chart: loki
      helm:
        valueFiles:
          - $values/charts/argocd-applications/values/loki-values.yaml
          - $values/charts/argocd-applications/values/loki-{{ required ".Values.cluster_name is required" .Values.cluster_name }}-values.yaml
        valuesObject:
          vault_name: '{{ required ".Values.vault_name is required" .Values.vault_name }}'
          cluster_name: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
          extraObjects:
            - apiVersion: v1
              kind: PersistentVolumeClaim
              metadata:
                name: loki-loki-data
                namespace: "loki"
              spec:
                accessModes:
                  - ReadWriteMany
                resources:
                  requests:
                    storage: 100Gi
                volumeName: loki-loki-data
                storageClassName: ""
            - apiVersion: v1
              kind: ConfigMap
              metadata:
                name: loki-data-source
                namespace: "loki"
                labels:
                  grafana_datasource: "1"
              data:
                datasource.yaml: |-
                  apiVersion: 1
                  datasources:
                    - name: Loki
                      uid: loki
                      type: loki
                      url: http://loki.loki.svc:3100
                      isDefault: false
                      jsonData:
                        httpHeaderName1: X-Scope-OrgID
                      secureJsonData:
                        httpHeaderValue1: "{{ .Values.cluster_name }}"
            - apiVersion: v1
              kind: PersistentVolume
              metadata:
                name: loki-loki-data
              spec:
                capacity:
                  storage: 100Gi
                accessModes:
                  - ReadWriteMany
                persistentVolumeReclaimPolicy: Retain
                nfs:
                  server: '{{ required ".Values.nfs_server is required" .Values.nfs_server }}'
                  path: '{{ required ".Values.cluster_nfs_path is required" .Values.cluster_nfs_path }}/loki-data'
    - repoURL: https://github.com/symmatree/tiles.git
      targetRevision: '{{ required ".Values.targetRevision is required" .Values.targetRevision }}'
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/warn: baseline
