#!/bin/bash
set -euxo pipefail

# This script applies Talos configuration after Terraform has created the VMs.
# It should be run after terraform apply, with environment variables loaded from
# 1Password misc-config (via 1password/load-secrets-action).

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Install required tools if not present
install_tools() {
	# Check and install talosctl
	if ! command -v talosctl &>/dev/null; then
		echo "Installing talosctl..."
		curl -Lo /tmp/talosctl "https://github.com/siderolabs/talos/releases/latest/download/talosctl-linux-amd64"
		chmod +x /tmp/talosctl
		sudo mv /tmp/talosctl /usr/local/bin/talosctl
		echo "Installed talosctl $(talosctl version --short)"
	else
		echo "talosctl already installed: $(talosctl version --short)"
	fi

	# Check and install 1Password CLI
	if ! command -v op &>/dev/null; then
		echo "Installing 1Password CLI..."
		# Add 1Password repository
		curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
		echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64/stable main' | sudo tee /etc/apt/sources.list.d/1password.list
		sudo apt-get update
		sudo apt-get install -y 1password-cli
		echo "Installed 1Password CLI"
	else
		echo "1Password CLI already installed: $(op --version)"
	fi

	# Check for envsubst (usually in gettext package)
	if ! command -v envsubst &>/dev/null; then
		echo "Installing envsubst (gettext)..."
		sudo apt-get update
		sudo apt-get install -y gettext-base
	fi
}

echo "::group::Install required tools"
install_tools
echo "::endgroup::"

# Required environment variables (should be loaded from 1Password misc-config)
required_vars=(
	"OP_SERVICE_ACCOUNT_TOKEN"
	"cluster_name"
	"pod_cidr"
	"service_cidr"
	"control_plane_vip"
	"control_plane_vip_link"
	"talos_install_image"
	"control_plane_ips"
	"bootstrap_ip"
	"vault_name"
	"machine_secrets"
)
# worker_ips is optional (may be empty if no workers)

# Validate required variables
missing_vars=()
for var in "${required_vars[@]}"; do
	if [[ -z ${!var:-} ]]; then
		missing_vars+=("$var")
	fi
done

if [[ ${#missing_vars[@]} -gt 0 ]]; then
	echo "Error: Missing required environment variables:" >&2
	printf "  - %s\n" "${missing_vars[@]}" >&2
	echo "These should be loaded from 1Password misc-config." >&2
	exit 1
fi

# Parse control plane IPs (comma-separated)
IFS=',' read -ra CONTROL_PLANE_IPS_ARRAY <<<"${control_plane_ips:-}"

echo "::group::Load Talos secrets"
# Secrets are generated by Terraform and loaded from environment variables
SECRETS_FILE="${SCRIPT_DIR}/secrets.yaml"
echo "${machine_secrets:-}" >"$SECRETS_FILE"
echo "Loaded machine secrets"
echo "::endgroup::"

echo "::group::Generate Talos machine configurations"
# Generate configs with patches
talosctl gen config "${cluster_name:-}" "https://${control_plane_vip:-}:6443" \
	--with-secrets "$SECRETS_FILE" \
	--config-patch "@${SCRIPT_DIR}/talos-config.yaml" \
	--config-patch-control-plane <(envsubst <"${SCRIPT_DIR}/common-patch.yaml.tmpl") \
	--config-patch-control-plane <(envsubst <"${SCRIPT_DIR}/layer2-vip-config.yaml.tmpl") \
	--config-patch-worker <(envsubst <"${SCRIPT_DIR}/common-patch.yaml.tmpl") \
	--with-docs=false \
	--with-examples=false

echo "Generated controlplane.yaml and worker.yaml"

# Configure talosconfig with endpoint and node
# CRITICAL: Use bootstrap IP for endpoint (VIP doesn't exist until etcd is up and Layer2VIPConfig is applied)
# The VIP won't work until after the cluster is fully bootstrapped
# This must be done before bootstrap/kubeconfig commands
talosctl --talosconfig ./talosconfig config endpoint "https://${bootstrap_ip:-}:6443"
talosctl --talosconfig ./talosconfig config node "${bootstrap_ip:-}"

# Verify the configuration
echo "Verifying talosconfig endpoint and node:"
talosctl --talosconfig ./talosconfig config info
echo "Configured talosconfig with endpoint=${bootstrap_ip} and node=${bootstrap_ip} (NOT using VIP ${control_plane_vip} yet)"

# Store talosconfig
op item edit \
	--vault "${vault_name:-}" \
	"${cluster_name:-}-talosconfig" \
	"notesPlain=$(cat talosconfig)" </dev/null
# Workaround for https://www.1password.community/discussions/developers/cli-still-has-a-bug-when-running-op-create-programmatically/23429

echo "::endgroup::"

echo "::group::Apply machine configurations to control plane nodes"
for node_ip in "${CONTROL_PLANE_IPS_ARRAY[@]}"; do
	echo "Applying config to control plane node: $node_ip"
	for attempt in {1..10}; do
		if talosctl apply-config \
			--insecure \
			--nodes "$node_ip" \
			--file controlplane.yaml; then
			echo "Successfully applied config to $node_ip"
			break
		fi
		if [[ $attempt -eq 10 ]]; then
			echo "Error: Failed to apply config to $node_ip after 10 attempts" >&2
			exit 1
		fi
		echo "  Attempt $attempt/10 failed, retrying in 5 seconds..."
		sleep 5
	done
done
echo "::endgroup::"

echo "::group::Apply machine configurations to worker nodes"
if [[ -n ${worker_ips:-} ]]; then
	IFS=',' read -ra WORKER_IPS_ARRAY <<<"$worker_ips"
	for node_ip in "${WORKER_IPS_ARRAY[@]}"; do
		if [[ -n $node_ip ]]; then
			echo "Applying config to worker node: $node_ip"
			for attempt in {1..10}; do
				if talosctl apply-config \
					--insecure \
					--nodes "$node_ip" \
					--file worker.yaml; then
					echo "Successfully applied config to $node_ip"
					break
				fi
				if [[ $attempt -eq 10 ]]; then
					echo "Error: Failed to apply config to $node_ip after 10 attempts" >&2
					exit 1
				fi
				echo "  Attempt $attempt/10 failed, retrying in 5 seconds..."
				sleep 5
			done
		fi
	done
else
	echo "No worker nodes to configure"
fi
echo "::endgroup::"

echo "::group::Bootstrap cluster and get kubeconfig"
# Bootstrap is idempotent - talosctl bootstrap will only bootstrap if not already bootstrapped
# Retry loop handles the case where node is in "Booting" state but ready for bootstrap
echo "Attempting to bootstrap cluster..."
for attempt in {1..30}; do
	if talosctl bootstrap --talosconfig talosconfig; then
		echo "Successfully bootstrapped cluster"
		break
	fi
	if [[ $attempt -eq 30 ]]; then
		echo "Error: Failed to bootstrap cluster after 30 attempts" >&2
		exit 1
	fi
	echo "  Attempt $attempt/30 failed, retrying in 10 seconds..."
	sleep 10
done

# Get kubeconfig (also idempotent - regenerates but doesn't break anything)
talosctl kubeconfig --talosconfig talosconfig
echo "::endgroup::"

echo "::group::Store talosconfig and kubeconfig in 1Password"
# Machine secrets are already in 1Password (generated by Terraform)
# Only store talosconfig and kubeconfig here

# Store kubeconfig
op item edit \
	--vault "$vault_name" \
	"${cluster_name}-kubeconfig" \
	"notesPlain=$(cat kubeconfig)" \
	2>/dev/null || op item create \
	--vault "$vault_name" \
	--category "Secure Note" \
	--title "${cluster_name}-kubeconfig" \
	"notesPlain=$(cat kubeconfig)"

echo "Stored talosconfig and kubeconfig in 1Password"
echo "::endgroup::"

# Cleanup
rm -f "${SCRIPT_DIR}/secrets.yaml" controlplane.yaml worker.yaml talosconfig kubeconfig

echo "Talos configuration applied successfully"
