apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ghcr-pull-secret
  namespace: "{{ .Release.Namespace }}"
type: kubernetes.io/dockerconfigjson
spec:
  itemPath: "vaults/{{ .Values.vault_name }}/items/jupyterhub-github-token"
