apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: hub-credentials
  namespace: "{{ .Release.Namespace }}"
spec:
  itemPath: "vaults/{{ .Values.vault_name }}/items/{{ .Values.cluster_name }}-jupyterhub-hub-credentials"
