apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ssh-secret
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: "vaults/{{ .Values.vault_name }}/items/jupyterhub-ssh-key"
