apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  namespace: "{{ .Release.Namespace }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.sshHostname }}"
spec:
  type: LoadBalancer
  selector:
    tiles.symmatree.com/user: seth
  ports:
    - name: ssh
      port: 22
      targetPort: 22
