name: "helm-setup"
description: "Install Helm and cache state"
inputs:
  helm_version:
    description: "Helm version to install"
    required: true
    default: "v3.18.4"
runs:
  using: "composite"
  steps:
    - name: Datestamp
      shell: bash
      id: stamps
      run: |
        set -euo pipefail
        echo "DATESTAMP=$(date +'%Y%m%d')" | tee -a "$GITHUB_OUTPUT"
    - name: Helm cache
      id: helm-cache
      uses: actions/cache@v4
      with:
        path: |
          **/charts/*.tgz
        key: ${{ runner.os }}-helm-${{ steps.stamps.outputs.DATESTAMP }}-${{ hashFiles('**/Chart.lock') }}
        restore-keys: |
          ${{ runner.os }}-helm-${{ steps.stamps.outputs.DATESTAMP }}-
          ${{ runner.os }}-helm-
    - name: Install helm
      uses: azure/setup-helm@v4.3.1
      with:
        version: "${{ inputs.helm_version }}"
    - name: Install Helm dependencies
      shell: bash
      if: steps.helm-cache.outputs.cache-hit != 'true'
      # cache-hit is only true for an exact match, including the date.
      run: |
        set -euo pipefail
        "${GITHUB_WORKSPACE}/ci-tools/helm-add-repos.sh"
        "${GITHUB_WORKSPACE}/ci-tools/helm-update-all.sh"
