name: "helm-setup"
description: "Install Helm and cache state"
inputs:
  helm_version:
    description: "Helm version to install"
    required: true
    default: "v3.19.4"
  debug:
    description: "Enable debug logging for cache key globs"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Datestamp
      shell: bash
      id: stamps
      run: |
        set -euo pipefail
        echo "DATESTAMP=$(date +'%Y%m%d')" | tee -a "$GITHUB_OUTPUT"
    - name: Debug cache key globs
      if: inputs.debug == 'true'
      shell: bash
      run: |
        set -euo pipefail
        echo "Cache key globs:"
        echo "  Chart.lock: **/Chart.lock"
        echo "  Chart.yaml: **/Chart.yaml"
        echo "  helm-cache-poison.txt: helm-cache-poison.txt"
        echo "Expanded Chart.lock files:"
        find . -name "Chart.lock" -type f | sort || echo "  (none found)"
        echo "Expanded Chart.yaml files:"
        find . -name "Chart.yaml" -type f | sort || echo "  (none found)"
    - name: Helm cache
      id: helm-cache
      uses: actions/cache@v4
      with:
        path: |
          **/charts/*.tgz
          ~/.config/helm/repositories.yaml
          ~/.cache/helm/repository
        key: ${{ runner.os }}-helm-${{ inputs.helm_version }}-${{ steps.stamps.outputs.DATESTAMP }}-${{ hashFiles('**/Chart.lock', '**/Chart.yaml', 'helm-cache-poison.txt') }}
        restore-keys: |
          ${{ runner.os }}-helm-${{ inputs.helm_version }}-${{ steps.stamps.outputs.DATESTAMP }}-
    - name: Install helm
      uses: azure/setup-helm@v4.3.1
      with:
        version: "${{ inputs.helm_version }}"
    - name: Install Helm dependencies
      shell: bash
      if: steps.helm-cache.outputs.cache-hit != 'true'
      # cache-hit is only true for an exact match, including the date.
      run: |
        set -euo pipefail
        "${GITHUB_WORKSPACE}/ci-tools/helm-add-repos.sh"
        "${GITHUB_WORKSPACE}/ci-tools/helm-update-all.sh"
