{{- range $name, $target := .Values.certSync }}
{{- if $target.enabled }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "{{ $target.onePasswordItem.name }}"
  namespace: "{{ $.Release.Namespace }}"
type: Opaque
spec:
  itemPath: "{{ $target.onePasswordItem.itemPath }}"
{{- end }}
{{- end }}
