{{- if .Values.synologyDsmSync.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "{{ .Values.synologyDsmSync.loginOnePasswordItem.name }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: "{{ .Values.synologyDsmSync.loginOnePasswordItem.itemPath }}"
{{- end }}
