{{- if .Values.homeassistantSshSync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-ha-ssh-sync" .Release.Name | quote }}
  namespace: "{{ .Release.Namespace }}"
data:
  run.sh: |
{{ .Files.Get "scripts/ha-ssh-sync-run.sh" | nindent 4 }}
{{- range .Values.homeassistantSshSync.certificates }}
    one "{{ .fqdn }}" "/certs/{{ .volumeMountPath }}/tls.crt" "/certs/{{ .volumeMountPath }}/tls.key"
{{- end }}
{{- end }}
