{{- if .Values.homeassistantSshSync.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: "{{ .Values.homeassistantSshSync.sshKeyOnePasswordItem.name }}"
  namespace: "{{ .Release.Namespace }}"
type: Opaque
spec:
  itemPath: "{{ .Values.homeassistantSshSync.sshKeyOnePasswordItem.itemPath }}"
{{- end }}
