variable "github_owner" {
  description = "GitHub owner (user or organization)"
  type        = string
}

variable "github_token" {
  description = "GitHub PAT token - used for provider authentication when not using GitHub App. Leave empty when using app_auth."
  type        = string
  sensitive   = true
  default     = ""

  validation {
    condition     = var.github_token == "" || (var.github_app_id == "" && var.github_app_installation_id == "" && var.github_app_pem_file == "")
    error_message = "Cannot use both github_token and GitHub App authentication. Set either github_token OR the github_app_* variables, not both."
  }
}

# GitHub App authentication variables (optional - use these instead of PAT for automated token generation)
variable "github_app_id" {
  description = "GitHub App ID for app-based authentication (alternative to PAT)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "github_app_installation_id" {
  description = "GitHub App Installation ID"
  type        = string
  sensitive   = true
  default     = ""
}

variable "github_app_pem_file" {
  description = "GitHub App private key PEM file content or path"
  type        = string
  sensitive   = true
  default     = ""
}

# Provider configuration with support for both PAT and GitHub App authentication
provider "github" {
  owner = var.github_owner

  # Use PAT authentication if token is provided
  token = var.github_token != "" ? var.github_token : null

  # Use GitHub App authentication if app credentials are provided
  dynamic "app_auth" {
    for_each = var.github_app_id != "" ? [1] : []
    content {
      id              = var.github_app_id
      installation_id = var.github_app_installation_id
      pem_file        = var.github_app_pem_file
    }
  }
}

# Store the GitHub credentials in 1Password with metadata
# When using PAT: stores the user-provided token
# When using GitHub App: stores the app credentials (ID, installation ID, PEM key)
module "github_tf_bootstrap_token" {
  source = "../modules/github-app-token"

  count = var.github_token != "" ? 1 : 0 # Only create when using PAT authentication

  vault_uuid        = data.onepassword_vault.tf_secrets.uuid
  token_name        = "github-tiles-tf-bootstrap"
  token_value       = var.github_token
  token_description = "GitHub PAT for Terraform provider in tf/bootstrap - manages GitHub repository configuration"

  expiration_days = 90

  token_permissions = {
    administration = "write"
    contents       = "write"
    metadata       = "read"
    secrets        = "write"
    workflows      = "write"
  }

  token_repositories = [github_repository.tiles.name]
}

# Store GitHub App credentials in 1Password (when using app authentication)
resource "onepassword_item" "github_app_credentials" {
  count = var.github_app_id != "" ? 1 : 0 # Only create when using App authentication

  vault    = data.onepassword_vault.tf_secrets.uuid
  title    = "github-app-tiles-tf"
  category = "password"

  password = var.github_app_pem_file

  section {
    label = "app_details"
    field {
      label = "app_id"
      value = var.github_app_id
    }
    field {
      label = "installation_id"
      value = var.github_app_installation_id
    }
    field {
      label = "token_lifetime"
      value = "1 hour (auto-generated by GitHub)"
    }
  }

  section {
    label = "metadata"
    field {
      label = "description"
      value = "GitHub App credentials for Terraform provider - generates short-lived tokens automatically"
    }
    field {
      label = "source"
      value = "managed by terraform"
    }
    field {
      label = "permissions"
      value = "administration:write, contents:write, metadata:read, secrets:write, workflows:write"
    }
  }
}

# Create token for Grafana GitHub data source
# NOTE: The token is refreshed by scripts/generate-github-app-token.sh which
# generates GitHub App installation tokens and stores the datasource.yaml configuration.
# See docs/github-app-setup.md for details.
module "grafana_github_token" {
  source = "../modules/github-app-token"

  vault_uuid        = data.onepassword_vault.tf_secrets.uuid
  token_name        = "grafana-github-token"
  token_value       = var.github_token # Initial token value (will be updated by script)
  token_username    = var.github_owner # Store organization/username for build scripts
  token_description = "GitHub token for Grafana GitHub data source - managed by generate-github-app-token.sh"
  # datasource_yaml is populated by the generate-github-app-token.sh script
}


resource "github_repository" "tiles" {
  name                   = "tiles"
  description            = "Infrastructure as Code for Tiles"
  visibility             = "public"
  has_issues             = true
  has_wiki               = false
  has_projects           = false
  allow_merge_commit     = false
  allow_auto_merge       = true
  allow_rebase_merge     = false
  allow_squash_merge     = true
  delete_branch_on_merge = true
  vulnerability_alerts   = true
  allow_update_branch    = true
  security_and_analysis {
    secret_scanning {
      status = "enabled"
    }
    secret_scanning_push_protection {
      status = "enabled"
    }
  }
}

resource "github_repository_ruleset" "tiles-main" {
  enforcement = "active"
  name        = "tiles-main"
  repository  = github_repository.tiles.name
  target      = "branch"
  bypass_actors {
    actor_id    = 5
    actor_type  = "RepositoryRole"
    bypass_mode = "pull_request"
  }
  conditions {
    ref_name {
      exclude = []
      include = ["~DEFAULT_BRANCH"]
    }
  }
  rules {
    creation                = true
    deletion                = true
    non_fast_forward        = true
    required_linear_history = true
    pull_request {
      required_approving_review_count = 0
    }
    required_status_checks {
      required_check {
        context        = "nodes-plan-apply"
        integration_id = 15368
      }
      required_check {
        context        = "pre-commit"
        integration_id = 15368
      }
    }
  }
}

resource "github_repository_ruleset" "tiles-tags" {
  name        = "tiles-tags"
  repository  = github_repository.tiles.name
  target      = "tag"
  enforcement = "active"

  bypass_actors {
    actor_id    = 5
    actor_type  = "RepositoryRole"
    bypass_mode = "always"
  }

  conditions {
    ref_name {
      include = ["refs/tags/test", "refs/tags/prod"]
      exclude = []
    }
  }

  rules {
    deletion = true
    update   = true
  }
}

module "secret_onepassword_sa_token" {
  source          = "../modules/github-secret"
  repository      = github_repository.tiles.name
  secret_name     = "ONEPASSWORD_SA_TOKEN"
  plaintext_value = var.onepassword_sa_token
}

resource "github_repository" "polisher" {
  name                   = "polisher"
  description            = "Infrastructure as Code for Polisher"
  visibility             = "public"
  has_issues             = true
  has_wiki               = false
  has_projects           = false
  allow_merge_commit     = false
  allow_auto_merge       = true
  allow_rebase_merge     = false
  allow_squash_merge     = true
  delete_branch_on_merge = true
  vulnerability_alerts   = true
  allow_update_branch    = true
  security_and_analysis {
    secret_scanning {
      status = "enabled"
    }
    secret_scanning_push_protection {
      status = "enabled"
    }
  }
}

resource "github_repository_ruleset" "polisher-main" {
  enforcement = "active"
  name        = "polisher-main"
  repository  = github_repository.polisher.name
  target      = "branch"
  bypass_actors {
    actor_id    = 5
    actor_type  = "RepositoryRole"
    bypass_mode = "pull_request"
  }
  conditions {
    ref_name {
      exclude = []
      include = ["~DEFAULT_BRANCH"]
    }
  }
  rules {
    creation                = true
    deletion                = true
    non_fast_forward        = true
    required_linear_history = true
    pull_request {
      required_approving_review_count = 0
    }
    required_status_checks {
      required_check {
        context        = "nodes-plan-apply"
        integration_id = 15368
      }
      required_check {
        context        = "pre-commit"
        integration_id = 15368
      }
    }
  }
}

resource "github_repository_ruleset" "polisher-tags" {
  name        = "polisher-tags"
  repository  = github_repository.polisher.name
  target      = "tag"
  enforcement = "active"

  bypass_actors {
    actor_id    = 5
    actor_type  = "RepositoryRole"
    bypass_mode = "always"
  }

  conditions {
    ref_name {
      include = ["refs/tags/test", "refs/tags/prod"]
      exclude = []
    }
  }

  rules {
    deletion = true
    update   = true
  }
}

module "secret_onepassword_sa_token_polisher" {
  source      = "../modules/github-secret"
  repository  = github_repository.polisher.name
  secret_name = "ONEPASSWORD_SA_TOKEN"
  # We share the 1password vault and service account
  plaintext_value = var.onepassword_sa_token
}
