apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  project: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
  sources:
    - repoURL: https://github.com/symmatree/tiles.git
      targetRevision: '{{ required ".Values.targetRevision is required" .Values.targetRevision }}'
      path: charts/cilium
      helm:
        valueFiles:
          - values.yaml
          - $values/charts/argocd-applications/values/cilium-values.yaml
          - $values/charts/argocd-applications/values/cilium-{{ required ".Values.cluster_name is required" .Values.cluster_name }}-values.yaml
        valuesObject:
          cilium:
            ipv4NativeRoutingCIDR: '{{ required ".Values.pod_cidr is required" .Values.pod_cidr }}'
            cluster:
              name: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}'
            hubble:
              tls:
                auto:
                  certManagerIssuerRef:
                    name: '{{ required ".Values.cluster_name is required" .Values.cluster_name }}-ca-issuer'
              ui:
                ingress:
                  hosts:
                    - 'hubble.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com'
                  tls:
                    - secretName: hubble-ui-tls
                      hosts:
                        - 'hubble.{{ required ".Values.cluster_name is required" .Values.cluster_name }}.symmatree.com'
    - repoURL: https://github.com/symmatree/tiles.git
      targetRevision: '{{ required ".Values.targetRevision is required" .Values.targetRevision }}'
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cilium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
