# Static Loki chart values. Templated keys in loki-application.yaml valuesObject.

extraObjects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: loki-loki-data
      namespace: "loki"
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Gi
      volumeName: loki-loki-data
      storageClassName: ""

loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  pattern_ingester:
    enabled: true
  limits_config:
    volume_enabled: true
  tracing:
    enabled: true
  ruler:
    enable_api: true
  storage:
    type: "filesystem"
    filesystem:
      chunks_directory: /mnt/loki-nfs/chunks
      rules_directory: /mnt/loki-nfs/rules
  querier:
    max_concurrent: 4
  extraMemberlistConfig:
    cluster_label: loki

deploymentMode: SingleBinary

monitoring:
  dashboards:
    enabled: false
  serviceMonitor:
    enabled: true
  rules:
    enabled: false
  selfMonitoring:
    enabled: false

minio:
  enabled: false

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    storageClassName: local-path
    enableStatefulSetAutoDeletePVC: true
  extraArgs:
    - -config.expand-env=true
    - -log-config-reverse-order
  extraVolumes:
    - name: loki-shared-storage
      persistentVolumeClaim:
        claimName: loki-loki-data
  extraVolumeMounts:
    - name: loki-shared-storage
      mountPath: /mnt/loki-nfs

gateway:
  enabled: false

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

chunksCache:
  enabled: false

resultsCache:
  enabled: false

ingester:
  replicas: 0

querier:
  replicas: 0

queryFrontend:
  replicas: 0

queryScheduler:
  replicas: 0

distributor:
  replicas: 0

compactor:
  replicas: 0

indexGateway:
  replicas: 0

bloomCompactor:
  replicas: 0

bloomGateway:
  replicas: 0
