# Resource overrides for tiles (prod). Same as pre-split monolithic valuesObject; tune here when raising prod requests/limits.

ingester:
  resources:
    requests:
      memory: 300Mi
kafka:
  resources:
    requests:
      memory: 256Mi

store_gateway:
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      memory: 1Gi
