name: build-mavproxy
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 9 * * *
jobs:
  build-mavproxy:
    permissions:
      contents: read
      id-token: write
      packages: write
    name: build-mavproxy
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/symmatree/tiles/mavproxy
      IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
      REGISTRY_USER: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ github.token }}
      MAVPROXY_VERSION: "1.8.74"
    steps:
      - uses: actions/checkout@v7

      - name: Docker Metadata
        id: docker-metadata
        uses: docker/metadata-action@v6
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          tags: |
            type=edge
            type=sha
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          context: ./containers/mavproxy
          containerfiles: |
            ./containers/mavproxy/Dockerfile
          build-args: |
            MAVPROXY_VERSION=${{ env.MAVPROXY_VERSION }}
          extra-args: |
            --disable-compression=false
            --cache-from=${{ env.IMAGE_NAME }}-cache
            --cache-to=${{ env.IMAGE_NAME }}-cache

      - name: Check images created
        run: buildah images | grep '${{ env.IMAGE_NAME }}'

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
